/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class inchi_InChIJNI */

#ifndef _Included_inchi_InChIJNI
#define _Included_inchi_InChIJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     inchi_InChIJNI
 * Method:    runInchi
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_inchi_InChIJNI_runInchi
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
